export function catchError(err) {
    console.log(err);
}