function catchError(err) {
    console.log(err);
}


export default catchError;